server:
  port: 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        ## Routing for auth service
        - id: auth-service-route
          uri: http://localhost:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        ## Routing for patient service
        - id: patient-service-route
          uri: http://localhost:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        ## REST-CLIENT: http://localhost:4004/api-docs/patients
        ## API-GATEWAY: http://patient-service:4000/v3/api-docs
        - id: api-docs-patient-service-route
          uri: http://localhost:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-service
          uri: http://localhost:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs
